name: Notify Live

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      youtube_link:
        description: 'YouTube stream link'
        required: true
        type: string
      title:
        description: 'Stream title'
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt


    - name: Run the disocrd live notification script
      run: python Livediscord.py
      env:
        YOUTUBE_LINK: ${{ github.event.inputs.youtube_link }}
        TITLE: ${{ github.event.inputs.title }}
        LIVE_DISCORD_WEBHOOK_URL: ${{ secrets.LIVE_DISCORD_WEBHOOK_URL }}

    - name: Run the X and BluSky live notification script
      run: python liveNotif.py
      env:
        YOUTUBE_LINK: ${{ github.event.inputs.youtube_link }}
        TITLE: ${{ github.event.inputs.title }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
